from datetime import datetime


def get_info(migration_id: str, message: str = "Just custom message place") -> str:
    info = f"# This file is auto-generated by the script builder.\n" + \
           f"# {message}\n" + f"# Migration ID: {migration_id}\n" + \
           f"# Migration date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} \n"

    return info


def get_upgrade_template() -> str:
    return "def upgrade(): \n"
