# This file is auto-generated by the script builder.
# Just custom message place
# Migration ID: test_script.py
# Migration date: 2023-01-06 20:15:41 

def upgrade(): 

    AlterTable('users', False,
               AlterColumn(Column('password', 'VARCHAR(40)', False, None, None, None, None),
                           ColumnNotNull(True),
                           ColumnDefault('xd')))
    ShowColumns('users')
