# This file is auto-generated by the script builder.
# Just custom message place
# Migration ID: test_script.py
# Migration date: 2023-01-09 01:19:10 

from database.ddl_base.ddl_composites import AlterTable, AlterColumn
from database.schema.column import Column
from database.ddl_base.ddl_leafs import ColumnNotNull, ColumnDefault, ShowColumns


def upgrade(): 

    AlterTable('users', False,
               AlterColumn(Column('password', 'VARCHAR(40)', False, None, None, None, None),
                           ColumnNotNull(True),
                           ColumnDefault('xd')))
    ShowColumns('users')
